name: 'NPM Binary Scanner'
description: 'Scans npm packages for binary executables and optionally uploads them to UnknownCyber for analysis'
author: 'UnknownCyber'

branding:
  icon: 'search'
  color: 'blue'

inputs:
  scan-path:
    description: 'Path to the directory containing node_modules to scan'
    required: false
    default: '.'
  deep-scan:
    description: 'Enable deep scan using magic bytes detection (slower but more thorough)'
    required: false
    default: 'false'
  upload:
    description: 'Upload found binaries to UnknownCyber API'
    required: false
    default: 'false'
  skip-existing:
    description: 'Skip uploading files that already exist in UnknownCyber (default: true)'
    required: false
    default: 'true'
  get-reputations:
    description: 'Fetch reputation data for existing files (default: true)'
    required: false
    default: 'true'
  api-url:
    description: 'UnknownCyber API URL'
    required: false
    default: 'https://api.unknowncyber.com'
  api-key:
    description: 'UnknownCyber API key for authentication'
    required: false
    default: ''
  repo:
    description: 'Repository name to tag uploads with (defaults to current GitHub repository)'
    required: false
    default: '${{ github.repository }}'

outputs:
  total-packages:
    description: 'Number of packages containing binaries'
  total-binaries:
    description: 'Total number of binary files found'
  results-file:
    description: 'Path to the JSON results file'
  upload-successful:
    description: 'Number of successfully uploaded files'
  upload-failed:
    description: 'Number of failed uploads'
  upload-skipped:
    description: 'Number of files skipped (already exist in UC)'
  threats-found:
    description: 'Number of files with HIGH or MEDIUM threat level'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Binary Scanner
      id: scan
      shell: bash
      env:
        SCAN_PATH: ${{ inputs.scan-path }}
        DEEP_SCAN: ${{ inputs.deep-scan }}
        UPLOAD: ${{ inputs.upload }}
        SKIP_EXISTING: ${{ inputs.skip-existing }}
        GET_REPUTATIONS: ${{ inputs.get-reputations }}
        UC_API_URL: ${{ inputs.api-url }}
        UC_API_KEY: ${{ inputs.api-key }}
        UC_REPO: ${{ inputs.repo }}
      run: |
        # Build command arguments
        ARGS=""
        if [ "$DEEP_SCAN" = "true" ]; then
          ARGS="$ARGS --deep"
        fi
        if [ "$UPLOAD" = "true" ]; then
          ARGS="$ARGS --upload"
        fi
        if [ "$SKIP_EXISTING" = "false" ]; then
          ARGS="$ARGS --force-upload"
        fi
        if [ "$GET_REPUTATIONS" = "false" ]; then
          ARGS="$ARGS --no-reputations"
        fi
        if [ -n "$UC_REPO" ]; then
          ARGS="$ARGS --repo $UC_REPO"
        fi
        
        # Run the scanner
        node "${{ github.action_path }}/scanner.js" $ARGS "$SCAN_PATH"
        
        # Parse results from JSON
        if [ -f "$SCAN_PATH/binary-scan-results.json" ]; then
          TOTAL_PACKAGES=$(node -e "console.log(require('./$SCAN_PATH/binary-scan-results.json').totalPackages)")
          TOTAL_BINARIES=$(node -e "console.log(require('./$SCAN_PATH/binary-scan-results.json').totalBinaries)")
          
          echo "total-packages=$TOTAL_PACKAGES" >> $GITHUB_OUTPUT
          echo "total-binaries=$TOTAL_BINARIES" >> $GITHUB_OUTPUT
          echo "results-file=$SCAN_PATH/binary-scan-results.json" >> $GITHUB_OUTPUT
          
          # Check for upload results
          UPLOAD_SUCCESS=$(node -e "const r = require('./$SCAN_PATH/binary-scan-results.json'); console.log(r.uploadResults?.successful?.length || 0)")
          UPLOAD_FAILED=$(node -e "const r = require('./$SCAN_PATH/binary-scan-results.json'); console.log(r.uploadResults?.failed?.length || 0)")
          UPLOAD_SKIPPED=$(node -e "const r = require('./$SCAN_PATH/binary-scan-results.json'); console.log(r.uploadResults?.skipped?.length || 0)")
          THREATS_FOUND=$(node -e "const r = require('./$SCAN_PATH/binary-scan-results.json'); const reps = r.uploadResults?.reputations || []; console.log(reps.filter(x => x.reputation && ['high','medium'].includes(x.reputation.overallThreatLevel)).length)")
          
          echo "upload-successful=$UPLOAD_SUCCESS" >> $GITHUB_OUTPUT
          echo "upload-failed=$UPLOAD_FAILED" >> $GITHUB_OUTPUT
          echo "upload-skipped=$UPLOAD_SKIPPED" >> $GITHUB_OUTPUT
          echo "threats-found=$THREATS_FOUND" >> $GITHUB_OUTPUT
        fi

    - name: Upload Results Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: binary-scan-results
        path: ${{ inputs.scan-path }}/binary-scan-results.json
        retention-days: 30
        overwrite: true

