# Example workflow: Scheduled weekly security scan
# Copy this file to your repo's .github/workflows/ directory

name: Weekly Binary Scan

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  weekly-scan:
    name: Weekly Binary Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Scan packages (deep scan)
        id: scan
        uses: Unknown-Cyber-Inc/uc-software-scan@v1
        with:
          deep-scan: 'true'
          upload: 'true'
          api-key: ${{ secrets.UC_API_KEY }}

      - name: Create Issue on New Binaries
        if: ${{ steps.scan.outputs.total-binaries != '0' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('binary-scan-results.json', 'utf8'));
            
            let body = `## Weekly Binary Scan Report\n\n`;
            body += `**Scan Date:** ${results.scanDate}\n\n`;
            body += `### Summary\n`;
            body += `- Packages with binaries: ${results.totalPackages}\n`;
            body += `- Total binary files: ${results.totalBinaries}\n\n`;
            
            body += `### Packages\n`;
            for (const pkg of results.packages) {
              body += `\n#### ${pkg.package} @ ${pkg.version}\n`;
              for (const file of pkg.files) {
                body += `- \`${file.file}\` (${file.type})\n`;
              }
            }
            
            if (results.uploadResults) {
              body += `\n### Upload Results\n`;
              body += `- Successful: ${results.uploadResults.successful.length}\n`;
              body += `- Failed: ${results.uploadResults.failed.length}\n`;
            }
            
            // Check if an issue already exists for this week
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'binary-scan',
              state: 'open'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Binary Scan Report - ${new Date().toISOString().split('T')[0]}`,
                body: body,
                labels: ['binary-scan', 'security']
              });
            }

