# Example workflow: Scan software packages on every push
# Copy this file to your repo's .github/workflows/ directory
# Customize the paths filter and install step for your ecosystem(s)

name: Security Scan

on:
  push:
    branches: [main, master]
    paths:
      # npm/Node.js
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      # Python/pip
      - 'requirements.txt'
      - 'requirements*.txt'
      - 'setup.py'
      - 'pyproject.toml'
      - 'Pipfile.lock'
      # Rust/Cargo
      - 'Cargo.toml'
      - 'Cargo.lock'
      # Go
      - 'go.mod'
      - 'go.sum'
      # Ruby
      - 'Gemfile'
      - 'Gemfile.lock'
      - '*.gemspec'
      # .NET/NuGet
      - '*.csproj'
      - 'packages.config'
      - '*.nuspec'
      # Maven/Java
      - 'pom.xml'
      - 'build.gradle'
      - 'build.gradle.kts'
  pull_request:
    branches: [main, master]
    paths:
      # npm/Node.js
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      # Python/pip
      - 'requirements.txt'
      - 'requirements*.txt'
      - 'setup.py'
      - 'pyproject.toml'
      - 'Pipfile.lock'
      # Rust/Cargo
      - 'Cargo.toml'
      - 'Cargo.lock'
      # Go
      - 'go.mod'
      - 'go.sum'
      # Ruby
      - 'Gemfile'
      - 'Gemfile.lock'
      - '*.gemspec'
      # .NET/NuGet
      - '*.csproj'
      - 'packages.config'
      - '*.nuspec'
      # Maven/Java
      - 'pom.xml'
      - 'build.gradle'
      - 'build.gradle.kts'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  scan-binaries:
    name: Scan for Binary Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Customize these setup/install steps for your ecosystem(s)
      # The scanner auto-detects packages after your build/install step
      
      # Example: Node.js/npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      # Example: Python/pip (uncomment if needed)
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      # - run: pip install -r requirements.txt

      - name: Scan packages
        id: scan
        uses: Unknown-Cyber-Inc/uc-software-scan@v1
        with:
          upload: 'true'
          api-key: ${{ secrets.UC_API_KEY }}

      - name: Report results
        run: |
          echo "## Binary Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Packages with binaries:** ${{ steps.scan.outputs.total-packages }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Total binary files:** ${{ steps.scan.outputs.total-binaries }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Uploaded successfully:** ${{ steps.scan.outputs.upload-successful }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Upload failures:** ${{ steps.scan.outputs.upload-failed }}" >> $GITHUB_STEP_SUMMARY

      - name: Fail on upload errors
        if: ${{ steps.scan.outputs.upload-failed != '0' }}
        run: |
          echo "::error::Some binary uploads failed. Check the scan results."
          exit 1

